CREATE DATABASE GROCERY;
USE GROCERY;
  
  
CREATE TABLE IF NOT EXISTS supplier ( 
    sup_id TINYINT PRIMARY KEY, 
    sup_name VARCHAR(255), 
    address TEXT 
);

SELECT * FROM supplier;

CREATE TABLE IF NOT EXISTS categories ( 
    cat_id TINYINT PRIMARY KEY, 
    cat_name VARCHAR(255) 
);

SELECT * FROM categories;

CREATE TABLE IF NOT EXISTS employees ( 
    emp_id TINYINT PRIMARY KEY, 
    emp_name VARCHAR(255), 
    hire_date VARCHAR(255) 
); 
  
SELECT * FROM employees;

CREATE TABLE IF NOT EXISTS customers ( 
    cust_id SMALLINT PRIMARY KEY, 
    cust_name VARCHAR(255), 
    address TEXT 
);

SELECT * FROM customers;

CREATE TABLE IF NOT EXISTS products ( 
    prod_id TINYINT PRIMARY KEY, 
    prod_name VARCHAR(255), 
    sup_id TINYINT, 
    cat_id TINYINT, 
    price DECIMAL(10,2), 
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
); 

SELECT * FROM products;

CREATE TABLE IF NOT EXISTS orders ( 
    ord_id SMALLINT PRIMARY KEY, 
    cust_id SMALLINT, 
    emp_id TINYINT, 
    order_date VARCHAR(255), 
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
); 

SELECT * FROM orders;

SELECT DISTINCT order_date FROM orders LIMIT 10;

UPDATE orders
SET order_date = TRIM(order_date);

UPDATE orders
SET order_date = STR_TO_DATE(order_date, '%m/%d/%Y');

ALTER TABLE orders MODIFY order_date DATE;

CREATE TABLE IF NOT EXISTS order_details ( 
ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY, 
ord_id SMALLINT, 
prod_id TINYINT, 
quantity TINYINT, 
each_price DECIMAL(10,2), 
total_price DECIMAL(10,2), 
FOREIGN KEY (ord_id) REFERENCES orders(ord_id) 
ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY (prod_id) REFERENCES products(prod_id) 
ON UPDATE CASCADE ON DELETE CASCADE 
); 

SELECT * FROM order_details;



ALTER TABLE employees ADD COLUMN hire_date_clean DATE;
UPDATE employees
SET hire_date_clean =
    CASE
        WHEN hire_date LIKE '%-%-%' THEN STR_TO_DATE(hire_date, '%d-%m-%Y')
        WHEN hire_date LIKE '%/%/%' THEN STR_TO_DATE(hire_date, '%m/%d/%Y')
    END;

ALTER TABLE employees DROP COLUMN hire_date;
ALTER TABLE employees CHANGE hire_date_clean hire_date DATE;

SELECT DATE_FORMAT(hire_date, '%d-%m-%Y') AS HireDate
FROM employees;


-- Customer Insights 
-- Gain an understanding of customer engagement and purchasing behavior. 
-- ● How many unique customers have placed orders? 
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders; 

-- ● Which customers have placed the highest number of orders? 
SELECT c.cust_id, c.cust_name, COUNT(o.ord_id) AS order_count
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY order_count DESC Limit 5;

-- ● What is the total and average purchase value per customer? 
SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase,
       AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC;

-- ● Who are the top 5 customers by total purchase amount?
SELECT c.cust_id, c.cust_name,
       SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;

-- 2. Product Performance 
-- Evaluate how well products are performing in terms of sales and revenue. 
-- ● How many products exist in each category? 
SELECT c.cat_id, c.cat_name, COUNT(p.prod_id) AS product_count
FROM categories c
LEFT JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name;

-- ● What is the average price of products by category? 
SELECT c.cat_id, c.cat_name, AVG(p.price) AS avg_price
FROM categories c
JOIN products p ON c.cat_id = p.cat_id
GROUP BY c.cat_id, c.cat_name;

-- ● Which products have the highest total sales volume (by quantity)? 
SELECT 
    p.prod_id, 
    p.prod_name, 
    SUM(od.quantity) AS total_quantity,
    SUM(od.total_price) AS total_sales
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_sales DESC
LIMIT 5;



-- ● What is the total revenue generated by each product? 
SELECT p.prod_id, p.prod_name, SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- ● How do product sales vary by category and supplier? 
SELECT c.cat_name, s.sup_name,
       SUM(od.quantity) AS total_quantity,
       SUM(od.total_price) AS total_revenue
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY c.cat_name, total_revenue DESC;

--  Sales and Order Trends 
-- Analyze business performance through orders and revenue over time. 
-- ● How many orders have been placed in total? 
SELECT COUNT(*) AS total_orders
FROM orders;

-- What is average value per order?
SELECT AVG(order_value) AS avg_order_value
FROM (
    SELECT o.ord_id, SUM(od.total_price) AS order_value
    FROM orders o
    JOIN order_details od 
      ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS order_totals;

-- ● On which dates were the most orders placed? 
SELECT order_date, COUNT(ord_id) AS order_count
FROM orders
GROUP BY order_date
ORDER BY order_count DESC LIMIT 5;

-- ● What are the monthly trends in order volume and revenue? 
SELECT DATE_FORMAT(o.order_date, '%Y-%m') AS month,
       COUNT(o.ord_id) AS order_count,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;

-- ● How do order patterns vary across weekdays and weekends?
SELECT CASE 
           WHEN DAYOFWEEK(o.order_date) IN (1,7) THEN 'Weekend'
           ELSE 'Weekday'
       END AS day_type,
       COUNT(o.ord_id) AS order_count,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_type;


-- Supplier Contribution 
-- Identify the most active and profitable suppliers. 
-- ● How many suppliers are there in the database? 
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- ● Which supplier provides the most products? 
SELECT s.sup_id, s.sup_name, COUNT(p.prod_id) AS product_count
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY product_count DESC limit 1;

-- ● What is the average price of products from each supplier? 
SELECT s.sup_id, s.sup_name, AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_price DESC;

-- ● Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_id, s.sup_name, SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

--  Employee Performance 
-- Assess how employees are handling and influencing sales. 
-- ● How many employees have processed orders? 
SELECT COUNT(DISTINCT emp_id) AS employees_with_orders
FROM orders;

-- ● Which employees have handled the most orders? 
SELECT e.emp_id, e.emp_name, COUNT(o.ord_id) AS order_count
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY order_count DESC limit 5;

-- ● What is the total sales value processed by each employee? 
SELECT e.emp_id, e.emp_name, SUM(od.total_price) AS total_sales_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

-- ● What is the average order value handled per employee?
SELECT e.emp_id, e.emp_name, AVG(order_value) AS avg_order_value
FROM employees e
JOIN (
    SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_value
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) AS subquery ON e.emp_id = subquery.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;

--  Order Details Deep Dive 
-- Explore item-level sales patterns and pricing behavior. 
-- ● What is the relationship between quantity ordered and total price? 
SELECT 
    quantity, 
    SUM(total_price) AS total_sales
FROM order_details
GROUP BY quantity
ORDER BY quantity;



-- ● What is the average quantity ordered per product? 
SELECT p.prod_id, p.prod_name, AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity DESC;




-- ● How does the unit price vary across products and orders? 
SELECT 
    o.ord_id,
    p.prod_id,
    p.prod_name,
    MIN(od.each_price) AS min_unit_price,
    MAX(od.each_price) AS max_unit_price,
    AVG(od.each_price) AS avg_unit_price
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
JOIN products p ON p.prod_id = od.prod_id
GROUP BY o.ord_id, p.prod_id, p.prod_name
ORDER BY avg_unit_price DESC;

